<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Colums-iMac.local" failures="1" tests="1" name="sample.HomepageTests" time="27.267" errors="0" timestamp="20 Oct 2020 20:09:03 GMT" skipped="0">
  <testcase classname="sample.HomepageTests" name="desktopTest" time="27.267">
    <failure message="number of blog posts incorrect
Expected: is &quot;blah&quot;
     but: was &quot;Hostels Worldwide - Online Hostel Bookings, Ratings and Reviews&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: number of blog posts incorrect
Expected: is "blah"
     but: was "Hostels Worldwide - Online Hostel Bookings, Ratings and Reviews"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at sample.HomepageTests.desktopTest(HomepageTests.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- desktopTest -->
</testsuite> <!-- sample.HomepageTests -->
